-   id: shfmt
    name: mvdan.cc/sh/v3/cmd/shfmt
    description: ''
    entry: shfmt
    language: golang
    'types': [shell]
    args: ["-w"]
    require_serial: false
    additional_dependencies: ["mvdan.cc/sh/v3/cmd/shfmt@v3.1.0"]
    minimum_pre_commit_version: '0'
